## Importing Libraries

In [1]:
!pip install nltk
!pip install bs4

Requirement already satisfied: nltk in C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages (3.9.4)
Requirement already satisfied: click in C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages (from nltk) (8.3.0)
Requirement already satisfied: joblib in C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: bs4 in C:\Users\ASUS\miniconda3\Lib\site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages (from bs4) (4.14.3)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages (from beautifulsoup4->bs4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\ASUS\AppData\Roaming\Python\Python313\site-packages (from beautifulsoup4->bs4) (4.15.0)

In [2]:
import nltk
import pandas as pd
import numpy as np
import tensorflow as tf
import string
from nltk.stem import PorterStemmer, WordNetLemmatizer
from bs4 import BeautifulSoup
from nltk.tokenize import word_tokenize

In [3]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download("punkt")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

## Loading Dataset

In [4]:
data = pd.read_csv('IMDB Dataset.csv')
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df = data.dropna()

In [ ]:
data.shape

(50000, 2)

In [ ]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

## Text Preprocessing

In [ ]:
punctuation = string.punctuation
stopwords = nltk.corpus.stopwords.words('english')
lm = WordNetLemmatizer()

In [ ]:
def clean_text(text):
    text = BeautifulSoup(text, "html.parser").get_text()
    text = "".join([char.lower() for char in text if char not in punctuation])
    tokens = word_tokenize(text)
    text = " ".join([lm.lemmatize(char) for char in tokens if char not in stopwords])
    return text

In [ ]:
nltk.download('punkt_tab')

X = df['review'].apply(lambda x: clean_text(x))

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [ ]:
Y = df = df['sentiment'].apply(lambda x: 1 if x == 'positive' else 0)

In [ ]:
Y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 50000, dtype: int64

In [ ]:
##Average num of words in text
sum=0
for i in X.to_list():
    sum+=len(i.split(" "))
avg = sum/len(X.to_list())
avg

119.84288

In [ ]:
#Splitting dataset
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,Embedding,TextVectorization, Dropout